### ISSUE TITLE
Final dist size

### ISSUE THREAD

**Issue by EhsanCh** [silvermine/videojs-quality-selector#12]
Hello
Final  silvermine-videojs-quality-selector.js is big !
videojs-resolution-switcher is only 14KB (7KB minified) 
And this plugin is about 60KB (19kb .min) ! 

is there anyway to reduce its size ?

**Comment by jthomerson** [comment]
@EhsanCh good observation. Looking into it, this is due to our requiring underscore. Ironically, that led me to realize that we don't actually declare underscore as a dependency, which we should (it is only listed as a dev dep). I'll fix that in 1.1.1.

Yes, we could get rid of the dependency on underscore, and maybe we should. However, we (the team that maintains silvermine software) use underscore extensively on hundreds of codebases because of its ease of use. That makes me not want to get rid of it just for the sake of a minor optimization. I call this minor because: 1) video.js is nearly 700k, and 2) if people are using this to watch video, they're going to be downloading megabytes of data, so this little bit of space saving isn't really helping them.

Code and people cost more than bandwidth, so I'm inclined not to "fix" this. Feel free to re-open if 1) you have an easy API-compatible replacement (like pulling in pieces of lodash), and 2) you want to open a pull request to make that change. I'll be happy to code review and merge it if it meets that criteria and our coding standards.

**Comment by jthomerson** [comment]
Thanks @EhsanCh !

**Comment by EhsanCh** [comment]
Hi Jeremy 
I think it is better to not include big dependencies (underscore) in final .js file.
instead should include it with <script> tag in html file.

There is many reasons to reduce js size (page speed and code efficiency and ...) , that you know them and i don't repeat them all ...
It may fix your needs , but it was the main reason that i (and someones like me ) didn't tried your good plugin at first ... 

Regards

**Comment by jthomerson** [comment]
@EhsanCh I agree in principle, but as stated above, am preferring the pragmatic approach over the strictest principled approach on this one. Still, if you want to submit a PR for a fix, we're happy to accept it. Thanks!
