### ISSUE TITLE
Issue with this plugin and videojs-preroll--quality selector button missing

### ISSUE THREAD

**Issue by z1lk** [silvermine/videojs-quality-selector#19]
The preroll plugin is https://github.com/dirkjanm/videojs-preroll, which uses [videojs-contrib-ads](https://github.com/videojs/videojs-contrib-ads).

When I load a preroll video, the quality selector fails. Specifically, `player.currentSources()` return only one source instead of multiple, and the menu attached to the button which contains the list of sources is  empty. I'm not super familiar with the videojs source and API but I have some leads after looking at the source for this plugin and videojs-preroll.
- videojs-preroll [sets the videojs source](https://github.com/dirkjanm/videojs-preroll/blob/master/src/videojs-preroll.js#L54), which at first I thought was the issue
- videojs-preroll relies on videojs-contrib-ads and uses its "linear ad mode", which takes a snapshot of the player state and restores it when the ad is finished. The snapshot seems to grab only the current source and not all sources. Here's a rough trace of all that:
  - [videojs-preroll starts linear ad mode](https://github.com/dirkjanm/videojs-preroll/blob/master/src/videojs-preroll.js#L51)
  - [videojs-contrib-ads preroll starts ad break](https://github.com/videojs/videojs-contrib-ads/blob/55df4b4cddd070750c60ea592c7408252c8b0ad1/src/states/Preroll.js#L158)
  - [videojs-contrib-ads adBreak gets a snapshot](https://github.com/videojs/videojs-contrib-ads/blob/59d90edbfafa18761901479f3214f065035c76fb/src/adBreak.js#L19)
  - [videojs-contrib-ads snapshot makes a snapshot with the current source](https://github.com/videojs/videojs-contrib-ads/blob/59d90edbfafa18761901479f3214f065035c76fb/src/snapshot.js#L34)

Anyway, I'm not sure where the problem is, but I'm looking for feedback on how to resolve this issue. I need both a preroll and quality selector, so I'm willing to open an issue on one of other repos and follow up here if needed, provide more info here, etc. Thanks!

**Comment by jthomerson** [comment]
Sorry, but we do not have the capacity to debug every issue for users. If you would like to report a defect or feature request, please provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). Still, we do not promise to implement feature requests because we are volunteers working on this project for free. Well-written pull requests to add features that show that they have a high quality and are well tested will be accepted if they comply with our [coding standards](https://github.com/silvermine/silvermine-info/blob/master/coding-standards.md).
