### ISSUE TITLE
show current quality on controlBar,

### ISSUE THREAD

**Issue by stfenjobs** [silvermine/videojs-quality-selector#28]
like this    https://www.bilibili.com/video/av24296298/

![image](https://user-images.githubusercontent.com/6580897/50486426-dfc02700-0a34-11e9-8079-2ce869540bec.png)

**Comment by find456789** [comment]
and thank you very much   silvermine

**Comment by jthomerson** [comment]
@find456789 I have no idea what you are requesting. I've pasted a screenshot below of what this plugin looks like. If you're requesting something different, please clearly explain what and why.

![image](https://user-images.githubusercontent.com/171934/50486716-2d06af00-09c9-11e9-89de-7d0412fae67b.png)

**Comment by find456789** [comment]
@jthomerson 

sorry, my english is not well


![image](https://user-images.githubusercontent.com/6580897/50512083-1d6f8f00-0acb-11e9-948f-0aed94303514.png)

**Comment by jthomerson** [comment]
@find456789 perfect, thanks!

@yokuze can you comment on how hard this would be? Or point @find456789 in the direction of where he'd need to look to make a PR to support this?

**Comment by yokuze** [comment]
Here's an outline of what it would take to implement this:

### A new plugin option

* We want to make displaying the selected quality label *optional*, so you'll need to add a new configuration option to the plugin. Follow the pattern set for user options here: https://github.com/silvermine/videojs-chromecast/blob/master/src/js/index.js#L25 Suggested name: `showQualitySelectionInMenu`
* Update the README to document this new option. Follow the pattern set here: https://github.com/silvermine/videojs-chromecast#initialization-options

### Modify components/QualitySelector.js to display the selected item

* In `components/QualitySelector.js`, check to see if the `showQualitySelectionInMenu` option is enabled and if it is, show the selected menu option's label instead of the icon
   * Note that `QualitySelector.js` inherits from Video.js' [MenuButton](https://github.com/videojs/video.js/blob/v7.2.2/src/js/menu/menu-button.js) component, so that would be a good place to look to see how the QualitySelector component's DOM is built
* When the selected menu item changes, update the label to be the selected menu option's label

@find456789 we'd be happy to accept a PR that follows the steps outlined above. Thanks!
