### ISSUE TITLE
Ogg & MP4 for same resolution

### ISSUE THREAD

**Issue by natiaz** [silvermine/videojs-quality-selector#34]
I'm trying to use mp4 & Ogg for each resolution, so the Ogg will be used when the user browser allows it. My problem is that when I set the source tags, the selector show all of them (mp4 & Ogg) and I want to show only the resolution, not the source itself.
Is there a way to accomplish this, maybe using a custom data to set the resolution (with multiple sources)?

Thanks in advance!

**Comment by yokuze** [comment]
Hi @natiaz. Currently, in this plugin, there is a 1-to-1 mapping between a quality selector menu item (e.g. "resolution") and a video source. It's not possible to have multiple sources for a single quality selector menu item.

However, instead of adding both OGG and MP4 sources to the player, would it make sense to use Video.js' [canPlayType](https://docs.videojs.com/player#canPlayType) method to check to see if OGG is supported by the browser's video player, and then only use the OGG sources if they are supported? I'm not sure how accurate that method is, but it could be something to look into.
