### ISSUE TITLE
Support persistence of selected resolution

### ISSUE THREAD

**Issue by silent10** [silvermine/videojs-quality-selector#66]
It would be nice if there was an option to persist the most recently selected resolution. Thoughts? Something like what this plugin does for volume: https://github.com/theonion/videojs-persistvolume

**Comment by jthomerson** [comment]
We opted not to provide this because no matter how we persist the setting, users will have to know its details so they can comply with GDPR and similar laws. But we made it easy to implement your own - when you provide the sources to the player, just set the `selected: true` flag on the one that you want selected. This gives you control, too, over what to do when different videos have different subsets of resolutions.
